version: "3"

services:
  minecraft:
    image: itzg/minecraft-server:adopt13
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
    environment:
      VERSION: "1.16.1"
      ONLINE_MODE: "FALSE"
      SERVER_NAME: "Archcraft"
      EULA: "TRUE"
    restart: always

volumes:
  mc:

